Посмотрите код страницы и вывод в консоль браузера.
<script>
    Promise._any = promises => {
        return new Promise((resolve, reject) => {
            if (promises.length === 0) resolve();
            else if (promises.every(item => !(item instanceof Promise))) setTimeout(() => resolve(), 100);

            promises.forEach((promise, i) => {
                if (promise instanceof Promise) {
                    promise.then((value) => {
                        resolve(value);
                    }, () => {
                        if (i === promises.length - 1) {
                            const error = new Error(`Все промисы с ошибками`);
                            reject(error);
                        }
                    })
                }
            })
        })
    }

    async function testPromiseAny() {
        let expect;

        expect = 'second';
        await Promise._any([
            new Promise((resolve, reject) => { setTimeout(() => { reject('first') }, 100) }),
            new Promise((resolve, reject) => { setTimeout(() => { resolve('second') }, 300) })
        ]).then(value => {
            console.log(`Promise._any завершился со значением ${value}, ожидаемое ${expect}`);
        })


        await Promise._any([
            new Promise((resolve, reject) => { setTimeout(() => { reject('first') }, 100) }),
            new Promise((resolve, reject) => { setTimeout(() => { reject('second') }, 300) })
        ]).catch(value => {
            console.log(`Promise._any завершился со значением ${value}`);
        })

        await Promise._any([]).then(value => {
            console.log(`Итерируемый объект пуст`);
        })

        expect = 'first';
        await Promise._any([1, 2,
            new Promise((resolve, reject) => { setTimeout(() => { resolve('first') }, 300) })
        ]).then(value => {
            console.log(`Promise._any завершился со значением ${value}, ожидаемое ${expect}`);
        })

        await Promise._any([1, 2, 3]).then(value => {
            console.log(`В массиве нет промисов`);
        })
    };



    Promise._allSettled = promises => {
        const results = [];
        return new Promise((resolve, reject) => {
            promises.forEach((promise, i) => {
                promise.then((value) => {
                    results.push({ value, 'status': 'fulfilled' });
                    if (i === promises.length - 1) {
                        resolve(results);
                    }
                }, (reason) => {
                    results.push({ reason, 'status': 'rejected' });
                    if (i === promises.length - 1) {
                        resolve(results);
                    }
                })
            })
        })
    }

    async function testAllSettledPromise() {
        await Promise._allSettled([
            new Promise((resolve, reject) => { setTimeout(() => { reject('first') }, 100) }),
            new Promise((resolve, reject) => { setTimeout(() => { resolve('second') }, 100) })
        ]).then(value => {
            console.log(`Promise._allSettled завершился со значением ${JSON.stringify(value)}`);
        })
    }



    Promise.prototype._finally = (func) => {
        return new Promise((resolve, reject) => {
            resolve(func());
        })
    }

    async function testFinallyPromise() {
        await Promise._allSettled([
            new Promise((resolve, reject) => { setTimeout(() => { reject('first') }, 100) }),
            new Promise((resolve, reject) => { setTimeout(() => { resolve('second') }, 100) })
        ])._finally(() => console.log('Функция onFinally вызвана'));
    }



    testPromiseAny().then(() => testAllSettledPromise()).then(() => testFinallyPromise().then(() => console.log('Метод finally возвращает Promise')));
</script>